INSERT INTO SOFTSKILLS (ID_SOFTSKILLS, pergunta, pontos, opcao_correta, dificuldade)
VALUES (SEQ_SOFTSKILLS.NEXTVAL,'Qual habilidades é fundamental para um bom trabalho em equipe? 
A) Falar alto
B) Chegar no horário
C) Ter mais conhecimento que o líder
D) Falar várias línguas
E) Empatia', 1, 'E', 0);

INSERT INTO SOFTSKILLS (ID_SOFTSKILLS, pergunta, pontos, opcao_correta, dificuldade)
VALUES (SEQ_SOFTSKILLS.NEXTVAL,'Como ser proativo no trabalho? 
A) Fazer somente quando é solicitado
B) Tomar ações preventivas e antecipar problemas
C) Fazer o trabalho do colega
D) Não se propor a aprender novas funções
E) Realizar apenas tarefas fáceis
', 1, 'B', 0);

INSERT INTO SOFTSKILLS (ID_SOFTSKILLS, pergunta, pontos, opcao_correta, dificuldade)
VALUES (SEQ_SOFTSKILLS.NEXTVAL,'Qual habilidade é fundamental para uma boa comunicação? 
A) Falar alto para ser ouvido por todos
B) Escutar ativamente
C) Utilizar vocabulário técnico
D) Falar o tempo todo para garantir que todos saibam que você está presente
E) Evitar contato visual para se concentrar nas palavras
', 1, 'B', 0);

INSERT INTO SOFTSKILLS (ID_SOFTSKILLS, pergunta, pontos, opcao_correta, dificuldade)
VALUES (SEQ_SOFTSKILLS.NEXTVAL,'Como a inteligência emocional agrega no ambiente profissional? 
A) Fazer o trabalho rápido 
B) Não tem necessidade de falar com os colegas
C) Ajuda em épocas de crise e no trabalho em equipe 
D) Não precisar pedir ajuda, quando estiver com dúvida 
E) Não leva em consideração o sentimento dos colegas ', 3, 'C', 1);

INSERT INTO SOFTSKILLS (ID_SOFTSKILLS, pergunta, pontos, opcao_correta, dificuldade)
VALUES (SEQ_SOFTSKILLS.NEXTVAL,'Qual soft skill é essencial para a capacidade de aceitar feedback construtivo e aplicá-lo para o aprimoramento pessoal e profissional?
A) Comunicação eficaz
B) Adaptabilidade
C) Empatia
D) Resolução de problemas
E) Inteligência emocional', 3, 'B', 1);

INSERT INTO SOFTSKILLS (ID_SOFTSKILLS, pergunta, pontos, opcao_correta, dificuldade)
VALUES (SEQ_SOFTSKILLS.NEXTVAL,'O que é resiliência no ambiente profissional? 
A) Não enfrentar os desafios 
B) Habilidade de se adaptar a mudanças e superar dificuldades 
C) Evitar qualquer tipo de risco 
D) Saber dizer “não” 
E) Fazer qualquer coisa que é solicitado ', 3, 'B', 1);

INSERT INTO SOFTSKILLS (ID_SOFTSKILLS, pergunta, pontos, opcao_correta, dificuldade)
VALUES (SEQ_SOFTSKILLS.NEXTVAL,'O que é empatia e como ela melhora o ambiente de trabalho? 
A) Dar presentes aos colegas
B) Capacidade de compreender e se colocar no lugar do outro
C) Expressar apenas emoções positivas para manter um ambiente agradável 
D) Falar somente o que o colega quer ouvir 
E) Somente dar feedback positivo', 3, 'B', 1);

INSERT INTO SOFTSKILLS (ID_SOFTSKILLS, pergunta, pontos, opcao_correta, dificuldade)
VALUES (SEQ_SOFTSKILLS.NEXTVAL,'Por que a gestão do tempo é essencial no ambiente profissional? 
A)  Para todos os colegas saberem quando deve ser feito a entrega
B) Gestão do tempo é essencial, somente em equipes grandes
C) Maximizar a produtividade e a eficiência
D) Não precisar controlar os prazos
E) Priorizar somente grandes projetos', 5, 'C', 2);

INSERT INTO SOFTSKILLS (ID_SOFTSKILLS, pergunta, pontos, opcao_correta, dificuldade)
VALUES (SEQ_SOFTSKILLS.NEXTVAL,'Qual é a importância da inclusão no local de trabalho? 
A)  Reduzir a inovação
B) Reduzir a criatividade
C) Ampliar perspectivas e promover um ambiente mais inclusivo 
D) Aumentar a competição entre os funcionários 
E) Evitar diferentes opiniões 
', 5, 'C', 2);

INSERT INTO SOFTSKILLS (ID_SOFTSKILLS, pergunta, pontos, opcao_correta, dificuldade)
VALUES (SEQ_SOFTSKILLS.NEXTVAL,'Como a resolução de problemas desafiadores contribui para o crescimento profissional? 
A) Reduzindo a capacidade analítica 
B) Diminuindo o aprendizado 
C) Desenvolvendo habilidades de resolução de problemas
D) Diminuindo a adaptabilidade 
E) Diminuindo a empatia', 5, 'C', 2);