CREATE USER VS_13_EQUIPE_9 IDENTIFIED BY oracle;

GRANT CONNECT TO VS_13_EQUIPE_9;

GRANT CONNECT, RESOURCE, DBA TO VS_13_EQUIPE_9;

GRANT CREATE SESSION TO VS_13_EQUIPE_9;

GRANT DBA TO VS_13_EQUIPE_9;

GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO VS_13_EQUIPE_9;

GRANT UNLIMITED TABLESPACE TO VS_13_EQUIPE_9;
GRANT CREATE MATERIALIZED VIEW TO VS_13_EQUIPE_9;
GRANT CREATE TABLE TO VS_13_EQUIPE_9;
GRANT GLOBAL QUERY REWRITE TO VS_13_EQUIPE_9;
GRANT SELECT ANY TABLE TO VS_13_EQUIPE_9;